title: Esha's Blog
author: Esha Bansal
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog I will discuss my favorite things to do and some of my personal interests.
  I hope people read and relate to my content!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
